import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { loadStripe} from '@stripe/stripe-js'
import { Elements } from '@stripe/react-stripe-js'
import { useEffect, useState } from 'react'

export default function Home() {

  const [publishableKey,setPublishableKey] = useState('')

  useEffect(() => {
   try{
    fetch('api/keys',{
      method: 'GET',
      headers:{'content-type':'application/json'}
    })
    .then((res) => res.json())
    .then((data) => setPublishableKey(data.publishableKey))
   }
   catch(err){console.log(err.message)}
  }
   
  )
  if(!publishableKey) {return 'loading...!'}


const stripe = loadStripe(publishableKey);


  return (
    <div className={styles.container}>
      <Head>
        <title>Payments! </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
       <span className='text-8xl text-purple-700'> Welcome to GetMagic Payments!! The safest way for Creators of all stripe to accept payments online!<span className='text-4xl'>and soon..offline :)</span></span>
      </main>
    
    </div>
  )
}
